// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user.proto

/*
Package user is a generated protocol buffer package.

It is generated from these files:
	proto/user.proto

It has these top-level messages:
	User
	Response
	ResponseUser
	RequestQuery
	ResponseList
	UserList
*/
package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id        string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	NetworkId string `protobuf:"bytes,2,opt,name=network_id,json=networkId" json:"network_id,omitempty"`
	FirstName string `protobuf:"bytes,3,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	LastName  string `protobuf:"bytes,4,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
	Email     string `protobuf:"bytes,5,opt,name=email" json:"email,omitempty"`
	Password  string `protobuf:"bytes,6,opt,name=password" json:"password,omitempty"`
	IsAdmin   string `protobuf:"bytes,7,opt,name=is_admin,json=isAdmin" json:"is_admin,omitempty"`
	CreatedAt string `protobuf:"bytes,8,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt string `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetNetworkId() string {
	if m != nil {
		return m.NetworkId
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetIsAdmin() string {
	if m != nil {
		return m.IsAdmin
	}
	return ""
}

func (m *User) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *User) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type Response struct {
	Result string            `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Error  map[string]string `protobuf:"bytes,2,rep,name=error" json:"error,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Data   map[string]string `protobuf:"bytes,3,rep,name=data" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *Response) GetError() map[string]string {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Response) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

type ResponseUser struct {
	Result string            `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Error  map[string]string `protobuf:"bytes,2,rep,name=error" json:"error,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Data   *User             `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *ResponseUser) Reset()                    { *m = ResponseUser{} }
func (m *ResponseUser) String() string            { return proto.CompactTextString(m) }
func (*ResponseUser) ProtoMessage()               {}
func (*ResponseUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ResponseUser) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *ResponseUser) GetError() map[string]string {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *ResponseUser) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

type RequestQuery struct {
	Offset  string `protobuf:"bytes,1,opt,name=offset" json:"offset,omitempty"`
	Limit   string `protobuf:"bytes,2,opt,name=limit" json:"limit,omitempty"`
	Orderby string `protobuf:"bytes,3,opt,name=orderby" json:"orderby,omitempty"`
	Sort    string `protobuf:"bytes,4,opt,name=sort" json:"sort,omitempty"`
}

func (m *RequestQuery) Reset()                    { *m = RequestQuery{} }
func (m *RequestQuery) String() string            { return proto.CompactTextString(m) }
func (*RequestQuery) ProtoMessage()               {}
func (*RequestQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RequestQuery) GetOffset() string {
	if m != nil {
		return m.Offset
	}
	return ""
}

func (m *RequestQuery) GetLimit() string {
	if m != nil {
		return m.Limit
	}
	return ""
}

func (m *RequestQuery) GetOrderby() string {
	if m != nil {
		return m.Orderby
	}
	return ""
}

func (m *RequestQuery) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

type ResponseList struct {
	Result string            `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Error  map[string]string `protobuf:"bytes,2,rep,name=error" json:"error,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Data   *UserList         `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *ResponseList) Reset()                    { *m = ResponseList{} }
func (m *ResponseList) String() string            { return proto.CompactTextString(m) }
func (*ResponseList) ProtoMessage()               {}
func (*ResponseList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ResponseList) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *ResponseList) GetError() map[string]string {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *ResponseList) GetData() *UserList {
	if m != nil {
		return m.Data
	}
	return nil
}

type UserList struct {
	Offset string  `protobuf:"bytes,1,opt,name=offset" json:"offset,omitempty"`
	Limit  string  `protobuf:"bytes,2,opt,name=limit" json:"limit,omitempty"`
	Count  string  `protobuf:"bytes,3,opt,name=count" json:"count,omitempty"`
	List   []*User `protobuf:"bytes,4,rep,name=list" json:"list,omitempty"`
}

func (m *UserList) Reset()                    { *m = UserList{} }
func (m *UserList) String() string            { return proto.CompactTextString(m) }
func (*UserList) ProtoMessage()               {}
func (*UserList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UserList) GetOffset() string {
	if m != nil {
		return m.Offset
	}
	return ""
}

func (m *UserList) GetLimit() string {
	if m != nil {
		return m.Limit
	}
	return ""
}

func (m *UserList) GetCount() string {
	if m != nil {
		return m.Count
	}
	return ""
}

func (m *UserList) GetList() []*User {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*Response)(nil), "user.Response")
	proto.RegisterType((*ResponseUser)(nil), "user.ResponseUser")
	proto.RegisterType((*RequestQuery)(nil), "user.RequestQuery")
	proto.RegisterType((*ResponseList)(nil), "user.ResponseList")
	proto.RegisterType((*UserList)(nil), "user.UserList")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UserService service

type UserServiceClient interface {
	Create(ctx context.Context, in *User, opts ...grpc.CallOption) (*Response, error)
	GetAll(ctx context.Context, in *RequestQuery, opts ...grpc.CallOption) (*ResponseList, error)
	GetUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*ResponseUser, error)
	UpdateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*Response, error)
	DeleteUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*Response, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Create(ctx context.Context, in *User, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/user.UserService/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetAll(ctx context.Context, in *RequestQuery, opts ...grpc.CallOption) (*ResponseList, error) {
	out := new(ResponseList)
	err := grpc.Invoke(ctx, "/user.UserService/GetAll", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*ResponseUser, error) {
	out := new(ResponseUser)
	err := grpc.Invoke(ctx, "/user.UserService/GetUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/user.UserService/UpdateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/user.UserService/DeleteUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceServer interface {
	Create(context.Context, *User) (*Response, error)
	GetAll(context.Context, *RequestQuery) (*ResponseList, error)
	GetUser(context.Context, *User) (*ResponseUser, error)
	UpdateUser(context.Context, *User) (*Response, error)
	DeleteUser(context.Context, *User) (*Response, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Create(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetAll(ctx, req.(*RequestQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _UserService_Create_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _UserService_GetAll_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserService_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UserService_DeleteUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/user.proto",
}

func init() { proto.RegisterFile("proto/user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 619 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xcd, 0x4e, 0x14, 0x41,
	0x10, 0xce, 0xcc, 0xfe, 0xcd, 0xd4, 0x9a, 0x0d, 0x96, 0x84, 0x0c, 0xa3, 0x18, 0x32, 0x27, 0x42,
	0x0c, 0x13, 0x97, 0x83, 0x84, 0x93, 0x1b, 0x20, 0xc4, 0xc4, 0x98, 0x88, 0xe1, 0xbc, 0x69, 0x98,
	0x82, 0xb4, 0xcc, 0x4e, 0xaf, 0xdd, 0x3d, 0x90, 0x8d, 0xf1, 0xe2, 0x2b, 0xf8, 0x2c, 0x1e, 0x7c,
	0x0e, 0x2f, 0x3e, 0x80, 0x8f, 0xe0, 0xd1, 0x83, 0xe9, 0xee, 0x99, 0x5d, 0x76, 0xc1, 0x44, 0xe4,
	0xd6, 0x5f, 0x7d, 0x5f, 0x7d, 0xa9, 0xfa, 0xba, 0x67, 0x60, 0x69, 0x2c, 0x85, 0x16, 0x69, 0xa9,
	0x48, 0x6e, 0xd9, 0x23, 0x36, 0xcd, 0x39, 0x7e, 0x72, 0x2e, 0xc4, 0x79, 0x4e, 0x29, 0x1b, 0xf3,
	0x94, 0x15, 0x85, 0xd0, 0x4c, 0x73, 0x51, 0x28, 0xa7, 0x49, 0x7e, 0x7b, 0xd0, 0x3c, 0x56, 0x24,
	0xb1, 0x07, 0x3e, 0xcf, 0x22, 0x6f, 0xdd, 0xdb, 0x08, 0x8f, 0x7c, 0x9e, 0xe1, 0x1a, 0x40, 0x41,
	0xfa, 0x4a, 0xc8, 0x8b, 0x21, 0xcf, 0x22, 0xdf, 0xd6, 0xc3, 0xaa, 0xf2, 0xca, 0xd2, 0x67, 0x5c,
	0x2a, 0x3d, 0x2c, 0xd8, 0x88, 0xa2, 0x86, 0xa3, 0x6d, 0xe5, 0x0d, 0x1b, 0x11, 0x3e, 0x86, 0x30,
	0x67, 0x35, 0xdb, 0xb4, 0x6c, 0x60, 0x0a, 0x96, 0x5c, 0x86, 0x16, 0x8d, 0x18, 0xcf, 0xa3, 0x96,
	0x25, 0x1c, 0xc0, 0x18, 0x82, 0x31, 0x53, 0xea, 0x4a, 0xc8, 0x2c, 0x6a, 0xbb, 0x8e, 0x1a, 0xe3,
	0x2a, 0x04, 0x5c, 0x0d, 0x59, 0x36, 0xe2, 0x45, 0xd4, 0xb1, 0x5c, 0x87, 0xab, 0x81, 0x81, 0x66,
	0x90, 0x53, 0x49, 0x4c, 0x53, 0x36, 0x64, 0x3a, 0x0a, 0xdc, 0x20, 0x55, 0x65, 0xa0, 0x0d, 0x5d,
	0x8e, 0xb3, 0x9a, 0x0e, 0x1d, 0x5d, 0x55, 0x06, 0x3a, 0xf9, 0xe5, 0x41, 0x70, 0x44, 0x6a, 0x2c,
	0x0a, 0x45, 0xb8, 0x02, 0x6d, 0x49, 0xaa, 0xcc, 0x75, 0x15, 0x43, 0x85, 0x30, 0x85, 0x16, 0x49,
	0x29, 0x64, 0xe4, 0xaf, 0x37, 0x36, 0xba, 0xfd, 0xd5, 0x2d, 0x9b, 0x71, 0xdd, 0xb6, 0x75, 0x60,
	0xb8, 0x83, 0x42, 0xcb, 0xc9, 0x91, 0xd3, 0xe1, 0x33, 0x68, 0x66, 0x4c, 0xb3, 0xa8, 0x61, 0xf5,
	0xd1, 0x82, 0x7e, 0x9f, 0x69, 0xe6, 0xe4, 0x56, 0x15, 0xef, 0x00, 0xcc, 0x2c, 0x70, 0x09, 0x1a,
	0x17, 0x34, 0xa9, 0x26, 0x30, 0x47, 0x13, 0xd7, 0x25, 0xcb, 0x4b, 0xaa, 0x2e, 0xc1, 0x81, 0x5d,
	0x7f, 0xc7, 0x8b, 0x5f, 0x40, 0x38, 0x35, 0xbb, 0x4b, 0x63, 0xf2, 0xd5, 0x83, 0x07, 0xf5, 0x3c,
	0xf6, 0xf6, 0xff, 0xb6, 0xfa, 0xf6, 0xfc, 0xea, 0x6b, 0xf3, 0xab, 0x98, 0xd6, 0x5b, 0xd6, 0x7f,
	0x3a, 0x5d, 0xdf, 0xdb, 0xe8, 0xf6, 0xc1, 0xf5, 0x18, 0xed, 0x7d, 0x17, 0x4e, 0xde, 0x9b, 0xb1,
	0x3f, 0x94, 0xa4, 0xf4, 0xdb, 0x92, 0xe4, 0xc4, 0x8c, 0x2d, 0xce, 0xce, 0x14, 0x4d, 0xc7, 0x76,
	0xc8, 0x38, 0xe4, 0x7c, 0xc4, 0x75, 0xed, 0x60, 0x01, 0x46, 0xd0, 0x11, 0x32, 0x23, 0x79, 0x32,
	0xa9, 0x1e, 0x6c, 0x0d, 0x11, 0xa1, 0xa9, 0x84, 0xd4, 0xd5, 0x4b, 0xb5, 0xe7, 0xe4, 0xdb, 0xb5,
	0x8c, 0x5e, 0x73, 0xa5, 0xff, 0x33, 0x23, 0xd3, 0x7a, 0x4b, 0x46, 0xc9, 0x5c, 0x46, 0xbd, 0x59,
	0x46, 0x46, 0x7f, 0xef, 0x9c, 0x0a, 0x08, 0x6a, 0xaf, 0x3b, 0x66, 0xb4, 0x0c, 0xad, 0x53, 0x51,
	0x16, 0xba, 0x4a, 0xc8, 0x01, 0x73, 0xa3, 0x39, 0x57, 0x26, 0x9f, 0xc6, 0xe2, 0x8d, 0x9a, 0x7a,
	0xff, 0x87, 0x0f, 0x5d, 0x03, 0xdf, 0x91, 0xbc, 0xe4, 0xa7, 0x84, 0xbb, 0xd0, 0xde, 0xb3, 0x9f,
	0x20, 0x5e, 0xd3, 0xc6, 0xbd, 0xf9, 0x64, 0x92, 0xe5, 0xcf, 0xdf, 0x7f, 0x7e, 0xf1, 0x7b, 0x49,
	0x98, 0x5e, 0x3e, 0xb7, 0xff, 0x2d, 0xb5, 0xeb, 0x6d, 0xe2, 0x1e, 0xb4, 0x0f, 0x49, 0x0f, 0xf2,
	0x1c, 0xb1, 0xd6, 0xcf, 0x6e, 0x3c, 0xc6, 0x9b, 0xe9, 0x26, 0x0f, 0xad, 0x4f, 0x17, 0x67, 0x3e,
	0x38, 0x80, 0xce, 0x21, 0x69, 0xfb, 0xb4, 0xaf, 0x4f, 0x80, 0x37, 0xdf, 0x6f, 0xb2, 0x62, 0xbb,
	0x97, 0xb0, 0x37, 0xed, 0x4e, 0x3f, 0xf2, 0xec, 0x13, 0xee, 0x01, 0x1c, 0xdb, 0xff, 0xc4, 0x0d,
	0x97, 0xc5, 0x3d, 0x56, 0xad, 0xc3, 0xa3, 0xfe, 0x82, 0x83, 0x59, 0xe6, 0x25, 0xc0, 0x3e, 0xe5,
	0xf4, 0x0f, 0x26, 0xd5, 0x18, 0x9b, 0x0b, 0x26, 0x27, 0x6d, 0xfb, 0x9f, 0xde, 0xfe, 0x13, 0x00,
	0x00, 0xff, 0xff, 0xaf, 0x43, 0x25, 0x24, 0xdf, 0x05, 0x00, 0x00,
}
