
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: public-deployment
  labels:
    app: public
spec:
  selector:
    matchLabels:
      app: public
  replicas: 1
  template:
    metadata:
      labels:
        app: public
    spec:
      containers:
      - name: public-service
        image: 755455355830.dkr.ecr.us-east-2.amazonaws.com/public-service
        env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        #ports:
        #- containerPort: 1883
        #imagePullPolicy: Always
        imagePullPolicy: Never
        ports:
        - name: public-service
          containerPort: 8180

---

apiVersion: v1
kind: Service
metadata:
  name: public-service
spec:
  type: NodePort
  selector:
    app: public
  ports:
  - port: 8180
    targetPort: public-service
