// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/public.proto

/*
Package public is a generated protocol buffer package.

It is generated from these files:
	proto/public.proto

It has these top-level messages:
	Network
	User
	Response
	LoginRequest
	UserMessage
*/
package public

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Network struct {
	Id        string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	ApiKey    string `protobuf:"bytes,3,opt,name=api_key,json=apiKey" json:"api_key,omitempty"`
	Secret    string `protobuf:"bytes,4,opt,name=secret" json:"secret,omitempty"`
	Status    string `protobuf:"bytes,5,opt,name=status" json:"status,omitempty"`
	CreatedAt string `protobuf:"bytes,6,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt string `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
}

func (m *Network) Reset()                    { *m = Network{} }
func (m *Network) String() string            { return proto.CompactTextString(m) }
func (*Network) ProtoMessage()               {}
func (*Network) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Network) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Network) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Network) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *Network) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *Network) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Network) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Network) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type User struct {
	Id        string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	NetworkId string `protobuf:"bytes,2,opt,name=network_id,json=networkId" json:"network_id,omitempty"`
	FirstName string `protobuf:"bytes,3,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	LastName  string `protobuf:"bytes,4,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
	Email     string `protobuf:"bytes,5,opt,name=email" json:"email,omitempty"`
	Password  string `protobuf:"bytes,6,opt,name=password" json:"password,omitempty"`
	IsAdmin   string `protobuf:"bytes,7,opt,name=is_admin,json=isAdmin" json:"is_admin,omitempty"`
	CreatedAt string `protobuf:"bytes,8,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt string `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetNetworkId() string {
	if m != nil {
		return m.NetworkId
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetIsAdmin() string {
	if m != nil {
		return m.IsAdmin
	}
	return ""
}

func (m *User) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *User) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type Response struct {
	Result string            `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Error  map[string]string `protobuf:"bytes,2,rep,name=error" json:"error,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Data   map[string]string `protobuf:"bytes,3,rep,name=data" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Response) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *Response) GetError() map[string]string {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Response) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

type LoginRequest struct {
	Email    string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserMessage struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *UserMessage) Reset()                    { *m = UserMessage{} }
func (m *UserMessage) String() string            { return proto.CompactTextString(m) }
func (*UserMessage) ProtoMessage()               {}
func (*UserMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UserMessage) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func init() {
	proto.RegisterType((*Network)(nil), "public.Network")
	proto.RegisterType((*User)(nil), "public.User")
	proto.RegisterType((*Response)(nil), "public.Response")
	proto.RegisterType((*LoginRequest)(nil), "public.LoginRequest")
	proto.RegisterType((*UserMessage)(nil), "public.UserMessage")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PublicService service

type PublicServiceClient interface {
	Register(ctx context.Context, in *User, opts ...grpc.CallOption) (*Response, error)
	Authenticate(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*Response, error)
}

type publicServiceClient struct {
	cc *grpc.ClientConn
}

func NewPublicServiceClient(cc *grpc.ClientConn) PublicServiceClient {
	return &publicServiceClient{cc}
}

func (c *publicServiceClient) Register(ctx context.Context, in *User, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/public.PublicService/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicServiceClient) Authenticate(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/public.PublicService/Authenticate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PublicService service

type PublicServiceServer interface {
	Register(context.Context, *User) (*Response, error)
	Authenticate(context.Context, *LoginRequest) (*Response, error)
}

func RegisterPublicServiceServer(s *grpc.Server, srv PublicServiceServer) {
	s.RegisterService(&_PublicService_serviceDesc, srv)
}

func _PublicService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/public.PublicService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicServiceServer).Register(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicService_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicServiceServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/public.PublicService/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicServiceServer).Authenticate(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PublicService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "public.PublicService",
	HandlerType: (*PublicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _PublicService_Register_Handler,
		},
		{
			MethodName: "Authenticate",
			Handler:    _PublicService_Authenticate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/public.proto",
}

func init() { proto.RegisterFile("proto/public.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 538 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xcd, 0x6e, 0xd3, 0x40,
	0x18, 0x94, 0x9d, 0xc4, 0x89, 0xbf, 0x06, 0x14, 0x56, 0x85, 0x1a, 0x87, 0x4a, 0x95, 0x0f, 0xa8,
	0xea, 0x21, 0x51, 0xcb, 0x81, 0x2a, 0x27, 0x22, 0xe8, 0xa1, 0x02, 0x2a, 0x94, 0x8a, 0xb3, 0xb5,
	0x8d, 0x3f, 0xcc, 0xaa, 0x8e, 0xd7, 0xec, 0xae, 0x53, 0xe5, 0xca, 0x2b, 0xf0, 0x14, 0xdc, 0x79,
	0x13, 0x5e, 0x81, 0x87, 0xe0, 0xc0, 0x01, 0xed, 0x8f, 0xd3, 0x92, 0x02, 0x52, 0x6f, 0x9e, 0x99,
	0xfd, 0x46, 0x3b, 0xb3, 0x9f, 0x81, 0x54, 0x82, 0x2b, 0x3e, 0xae, 0xea, 0x8b, 0x82, 0xcd, 0x47,
	0x06, 0x90, 0xc0, 0xa2, 0xf8, 0x49, 0xce, 0x79, 0x5e, 0xe0, 0x98, 0x56, 0x6c, 0x4c, 0xcb, 0x92,
	0x2b, 0xaa, 0x18, 0x2f, 0xa5, 0x3d, 0x95, 0x7c, 0xf3, 0xa0, 0x7b, 0x86, 0xea, 0x8a, 0x8b, 0x4b,
	0x72, 0x1f, 0x7c, 0x96, 0x45, 0xde, 0x9e, 0xb7, 0x1f, 0xce, 0x7c, 0x96, 0x11, 0x02, 0xed, 0x92,
	0x2e, 0x30, 0xf2, 0x0d, 0x63, 0xbe, 0xc9, 0x0e, 0x74, 0x69, 0xc5, 0xd2, 0x4b, 0x5c, 0x45, 0x2d,
	0x43, 0x07, 0xb4, 0x62, 0xaf, 0x71, 0x45, 0x1e, 0x41, 0x20, 0x71, 0x2e, 0x50, 0x45, 0x6d, 0xcb,
	0x5b, 0x64, 0x78, 0x45, 0x55, 0x2d, 0xa3, 0x8e, 0xe3, 0x0d, 0x22, 0xbb, 0x00, 0x73, 0x81, 0x54,
	0x61, 0x96, 0x52, 0x15, 0x05, 0x46, 0x0b, 0x1d, 0x33, 0x55, 0x5a, 0xae, 0xab, 0xac, 0x91, 0xbb,
	0x56, 0x76, 0xcc, 0x54, 0x25, 0xbf, 0x3c, 0x68, 0xbf, 0x97, 0x28, 0x6e, 0xdd, 0x79, 0x17, 0xa0,
	0xb4, 0x71, 0x52, 0x96, 0xb9, 0x9b, 0x87, 0x8e, 0x39, 0x35, 0xf2, 0x07, 0x26, 0xa4, 0x4a, 0x4d,
	0x30, 0x9b, 0x20, 0x34, 0xcc, 0x99, 0x4e, 0x37, 0x84, 0xb0, 0xa0, 0x8d, 0x6a, 0x73, 0xf4, 0x34,
	0x61, 0xc4, 0x6d, 0xe8, 0xe0, 0x82, 0xb2, 0xc2, 0x05, 0xb1, 0x80, 0xc4, 0xd0, 0xab, 0xa8, 0x94,
	0x57, 0x5c, 0x64, 0x2e, 0xc5, 0x1a, 0x93, 0xc7, 0xd0, 0x63, 0x32, 0xa5, 0xd9, 0x82, 0x95, 0x2e,
	0x42, 0x97, 0xc9, 0xa9, 0x86, 0x1b, 0xf1, 0x7b, 0xff, 0x8f, 0x1f, 0x6e, 0xc6, 0xff, 0xe9, 0x41,
	0x6f, 0x86, 0xb2, 0xe2, 0xa5, 0x44, 0xdd, 0xb0, 0x40, 0x59, 0x17, 0xca, 0xd5, 0xe0, 0x10, 0x39,
	0x84, 0x0e, 0x0a, 0xc1, 0x45, 0xe4, 0xef, 0xb5, 0xf6, 0xb7, 0x8e, 0x86, 0x23, 0xb7, 0x1e, 0xcd,
	0xe0, 0xe8, 0x44, 0xab, 0x27, 0xa5, 0x12, 0xab, 0x99, 0x3d, 0x49, 0x46, 0xd0, 0xce, 0xa8, 0xa2,
	0x51, 0xcb, 0x4c, 0xc4, 0xb7, 0x26, 0x5e, 0x51, 0x45, 0xed, 0x80, 0x39, 0x17, 0x1f, 0x03, 0x5c,
	0x9b, 0x90, 0x01, 0xb4, 0xf4, 0x5e, 0xd8, 0x5b, 0xe8, 0x4f, 0x5d, 0xd9, 0x92, 0x16, 0x75, 0xb3,
	0x42, 0x16, 0x4c, 0xfc, 0x63, 0x2f, 0x7e, 0x0e, 0xe1, 0xda, 0xec, 0x2e, 0x83, 0xc9, 0x0b, 0xe8,
	0xbf, 0xe1, 0x39, 0x2b, 0x67, 0xf8, 0xa9, 0x46, 0xa9, 0xae, 0x5f, 0xc5, 0xfb, 0xd7, 0xab, 0xf8,
	0x7f, 0xbe, 0x4a, 0xf2, 0x14, 0xb6, 0xf4, 0xea, 0xbc, 0x45, 0x29, 0x69, 0x6e, 0x36, 0xba, 0x96,
	0x28, 0xd2, 0xf5, 0x1a, 0x05, 0x1a, 0x9e, 0x66, 0x47, 0x5f, 0x3d, 0xb8, 0xf7, 0xce, 0x14, 0x70,
	0x8e, 0x62, 0xc9, 0xe6, 0x48, 0x5e, 0xea, 0xd6, 0x73, 0x26, 0x15, 0x0a, 0xd2, 0x6f, 0xca, 0xd1,
	0x5e, 0xf1, 0x60, 0xb3, 0xaa, 0x64, 0xe7, 0xf3, 0xf7, 0x1f, 0x5f, 0xfc, 0x07, 0x49, 0x7f, 0xbc,
	0x3c, 0x1c, 0x0b, 0x37, 0x35, 0xf1, 0x0e, 0xc8, 0x39, 0xf4, 0xa7, 0xb5, 0xfa, 0x88, 0xa5, 0x62,
	0x73, 0xaa, 0x90, 0x6c, 0x37, 0xa3, 0x37, 0x63, 0xfd, 0xc5, 0x70, 0x68, 0x0c, 0x1f, 0x26, 0x03,
	0x6d, 0x48, 0x6f, 0x38, 0x4c, 0xbc, 0x83, 0x8b, 0xc0, 0xfc, 0xcd, 0xcf, 0x7e, 0x07, 0x00, 0x00,
	0xff, 0xff, 0xee, 0x80, 0x55, 0xe1, 0x09, 0x04, 0x00, 0x00,
}
