// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/role.proto

/*
Package role is a generated protocol buffer package.

It is generated from these files:
	proto/role.proto

It has these top-level messages:
	Role
	Response
	ResponseRole
	RequestSearch
	ResponseList
	RoleList
*/
package role

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Role struct {
	Id        string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	NetworkId string `protobuf:"bytes,2,opt,name=network_id,json=networkId" json:"network_id,omitempty"`
	Title     string `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	RoleType  string `protobuf:"bytes,4,opt,name=role_type,json=roleType" json:"role_type,omitempty"`
	CreatedAt string `protobuf:"bytes,5,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt string `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
}

func (m *Role) Reset()                    { *m = Role{} }
func (m *Role) String() string            { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()               {}
func (*Role) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Role) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Role) GetNetworkId() string {
	if m != nil {
		return m.NetworkId
	}
	return ""
}

func (m *Role) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Role) GetRoleType() string {
	if m != nil {
		return m.RoleType
	}
	return ""
}

func (m *Role) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Role) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type Response struct {
	Result string            `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Error  map[string]string `protobuf:"bytes,2,rep,name=error" json:"error,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Data   map[string]string `protobuf:"bytes,3,rep,name=data" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *Response) GetError() map[string]string {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Response) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

type ResponseRole struct {
	Result string            `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Error  map[string]string `protobuf:"bytes,2,rep,name=error" json:"error,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Data   *Role             `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *ResponseRole) Reset()                    { *m = ResponseRole{} }
func (m *ResponseRole) String() string            { return proto.CompactTextString(m) }
func (*ResponseRole) ProtoMessage()               {}
func (*ResponseRole) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ResponseRole) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *ResponseRole) GetError() map[string]string {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *ResponseRole) GetData() *Role {
	if m != nil {
		return m.Data
	}
	return nil
}

type RequestSearch struct {
	Offset  string `protobuf:"bytes,1,opt,name=offset" json:"offset,omitempty"`
	Limit   string `protobuf:"bytes,2,opt,name=limit" json:"limit,omitempty"`
	Orderby string `protobuf:"bytes,3,opt,name=orderby" json:"orderby,omitempty"`
	Sort    string `protobuf:"bytes,4,opt,name=sort" json:"sort,omitempty"`
}

func (m *RequestSearch) Reset()                    { *m = RequestSearch{} }
func (m *RequestSearch) String() string            { return proto.CompactTextString(m) }
func (*RequestSearch) ProtoMessage()               {}
func (*RequestSearch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RequestSearch) GetOffset() string {
	if m != nil {
		return m.Offset
	}
	return ""
}

func (m *RequestSearch) GetLimit() string {
	if m != nil {
		return m.Limit
	}
	return ""
}

func (m *RequestSearch) GetOrderby() string {
	if m != nil {
		return m.Orderby
	}
	return ""
}

func (m *RequestSearch) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

type ResponseList struct {
	Result string            `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Error  map[string]string `protobuf:"bytes,2,rep,name=error" json:"error,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Data   *RoleList         `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *ResponseList) Reset()                    { *m = ResponseList{} }
func (m *ResponseList) String() string            { return proto.CompactTextString(m) }
func (*ResponseList) ProtoMessage()               {}
func (*ResponseList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ResponseList) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *ResponseList) GetError() map[string]string {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *ResponseList) GetData() *RoleList {
	if m != nil {
		return m.Data
	}
	return nil
}

type RoleList struct {
	Offset string  `protobuf:"bytes,1,opt,name=offset" json:"offset,omitempty"`
	Limit  string  `protobuf:"bytes,2,opt,name=limit" json:"limit,omitempty"`
	Count  string  `protobuf:"bytes,3,opt,name=count" json:"count,omitempty"`
	List   []*Role `protobuf:"bytes,4,rep,name=list" json:"list,omitempty"`
}

func (m *RoleList) Reset()                    { *m = RoleList{} }
func (m *RoleList) String() string            { return proto.CompactTextString(m) }
func (*RoleList) ProtoMessage()               {}
func (*RoleList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RoleList) GetOffset() string {
	if m != nil {
		return m.Offset
	}
	return ""
}

func (m *RoleList) GetLimit() string {
	if m != nil {
		return m.Limit
	}
	return ""
}

func (m *RoleList) GetCount() string {
	if m != nil {
		return m.Count
	}
	return ""
}

func (m *RoleList) GetList() []*Role {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*Role)(nil), "role.Role")
	proto.RegisterType((*Response)(nil), "role.Response")
	proto.RegisterType((*ResponseRole)(nil), "role.ResponseRole")
	proto.RegisterType((*RequestSearch)(nil), "role.RequestSearch")
	proto.RegisterType((*ResponseList)(nil), "role.ResponseList")
	proto.RegisterType((*RoleList)(nil), "role.RoleList")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RoleService service

type RoleServiceClient interface {
	Create(ctx context.Context, in *Role, opts ...grpc.CallOption) (*Response, error)
	GetAll(ctx context.Context, in *RequestSearch, opts ...grpc.CallOption) (*ResponseList, error)
	GetRole(ctx context.Context, in *Role, opts ...grpc.CallOption) (*ResponseRole, error)
	UpdateRole(ctx context.Context, in *Role, opts ...grpc.CallOption) (*Response, error)
}

type roleServiceClient struct {
	cc *grpc.ClientConn
}

func NewRoleServiceClient(cc *grpc.ClientConn) RoleServiceClient {
	return &roleServiceClient{cc}
}

func (c *roleServiceClient) Create(ctx context.Context, in *Role, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/role.RoleService/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleServiceClient) GetAll(ctx context.Context, in *RequestSearch, opts ...grpc.CallOption) (*ResponseList, error) {
	out := new(ResponseList)
	err := grpc.Invoke(ctx, "/role.RoleService/GetAll", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleServiceClient) GetRole(ctx context.Context, in *Role, opts ...grpc.CallOption) (*ResponseRole, error) {
	out := new(ResponseRole)
	err := grpc.Invoke(ctx, "/role.RoleService/GetRole", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleServiceClient) UpdateRole(ctx context.Context, in *Role, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/role.RoleService/UpdateRole", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RoleService service

type RoleServiceServer interface {
	Create(context.Context, *Role) (*Response, error)
	GetAll(context.Context, *RequestSearch) (*ResponseList, error)
	GetRole(context.Context, *Role) (*ResponseRole, error)
	UpdateRole(context.Context, *Role) (*Response, error)
}

func RegisterRoleServiceServer(s *grpc.Server, srv RoleServiceServer) {
	s.RegisterService(&_RoleService_serviceDesc, srv)
}

func _RoleService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Role)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/role.RoleService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).Create(ctx, req.(*Role))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestSearch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/role.RoleService/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).GetAll(ctx, req.(*RequestSearch))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleService_GetRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Role)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).GetRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/role.RoleService/GetRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).GetRole(ctx, req.(*Role))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleService_UpdateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Role)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).UpdateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/role.RoleService/UpdateRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).UpdateRole(ctx, req.(*Role))
	}
	return interceptor(ctx, in, info, handler)
}

var _RoleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "role.RoleService",
	HandlerType: (*RoleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _RoleService_Create_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _RoleService_GetAll_Handler,
		},
		{
			MethodName: "GetRole",
			Handler:    _RoleService_GetRole_Handler,
		},
		{
			MethodName: "UpdateRole",
			Handler:    _RoleService_UpdateRole_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/role.proto",
}

func init() { proto.RegisterFile("proto/role.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 571 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0x96, 0x9d, 0x3f, 0x6d, 0x26, 0xbf, 0x5f, 0x14, 0xa6, 0x51, 0xe5, 0x06, 0x8a, 0x2a, 0x9f,
	0xa2, 0x0a, 0xc5, 0x22, 0x3d, 0x50, 0xe5, 0x16, 0xb5, 0x55, 0x85, 0xc4, 0x29, 0x85, 0x73, 0xe4,
	0xc6, 0xd3, 0xb2, 0xca, 0xe2, 0x35, 0xeb, 0x49, 0x50, 0x84, 0xb8, 0xf0, 0x0a, 0x1c, 0x78, 0x03,
	0xde, 0x80, 0x03, 0xcf, 0xc1, 0x2b, 0xf0, 0x08, 0x3c, 0x00, 0xda, 0xb5, 0x9d, 0xbf, 0xe5, 0x50,
	0x7a, 0xdb, 0x6f, 0xe6, 0x9b, 0xcf, 0x33, 0xdf, 0x8e, 0x17, 0x9a, 0x89, 0x56, 0xac, 0x02, 0xad,
	0x24, 0x75, 0xed, 0x11, 0xcb, 0xe6, 0xdc, 0x7e, 0x72, 0xab, 0xd4, 0xad, 0xa4, 0x20, 0x4c, 0x44,
	0x10, 0xc6, 0xb1, 0xe2, 0x90, 0x85, 0x8a, 0xd3, 0x8c, 0xe3, 0x7f, 0x73, 0xa0, 0x3c, 0x54, 0x92,
	0xb0, 0x01, 0xae, 0x88, 0x3c, 0xe7, 0xc8, 0xe9, 0xd4, 0x86, 0xae, 0x88, 0xf0, 0x10, 0x20, 0x26,
	0xfe, 0xa0, 0xf4, 0x64, 0x24, 0x22, 0xcf, 0xb5, 0xf1, 0x5a, 0x1e, 0x79, 0x19, 0x61, 0x0b, 0x2a,
	0x2c, 0x58, 0x92, 0x57, 0xb2, 0x99, 0x0c, 0xe0, 0x63, 0xa8, 0x99, 0x6f, 0x8e, 0x78, 0x9e, 0x90,
	0x57, 0xb6, 0x99, 0x5d, 0x13, 0x78, 0x3d, 0x4f, 0xc8, 0x28, 0x8e, 0x35, 0x85, 0x4c, 0xd1, 0x28,
	0x64, 0xaf, 0x92, 0x29, 0xe6, 0x91, 0x01, 0x9b, 0xf4, 0x34, 0x89, 0x8a, 0x74, 0x35, 0x4b, 0xe7,
	0x91, 0x01, 0xfb, 0xbf, 0x1d, 0xd8, 0x1d, 0x52, 0x9a, 0xa8, 0x38, 0x25, 0xdc, 0x87, 0xaa, 0xa6,
	0x74, 0x2a, 0x39, 0x6f, 0x38, 0x47, 0x18, 0x40, 0x85, 0xb4, 0x56, 0xda, 0x73, 0x8f, 0x4a, 0x9d,
	0x7a, 0xef, 0xa0, 0x6b, 0xdd, 0x28, 0xca, 0xba, 0x17, 0x26, 0x77, 0x11, 0xb3, 0x9e, 0x0f, 0x33,
	0x1e, 0x3e, 0x83, 0x72, 0x14, 0x72, 0xe8, 0x95, 0x2c, 0xdf, 0xdb, 0xe0, 0x9f, 0x87, 0x1c, 0x66,
	0x74, 0xcb, 0x6a, 0x9f, 0x02, 0x2c, 0x25, 0xb0, 0x09, 0xa5, 0x09, 0xcd, 0xf3, 0x0e, 0xcc, 0xd1,
	0x98, 0x32, 0x0b, 0xe5, 0x94, 0x72, 0xbb, 0x32, 0xd0, 0x77, 0x4f, 0x9d, 0xf6, 0x0b, 0xa8, 0x2d,
	0xc4, 0xee, 0x53, 0xe8, 0x7f, 0x77, 0xe0, 0xbf, 0xa2, 0x1f, 0x7b, 0x4f, 0x7f, 0x1b, 0xfd, 0x64,
	0x7d, 0xf4, 0xc3, 0xf5, 0x51, 0x4c, 0xe9, 0x1d, 0xe3, 0x3f, 0x5d, 0x8c, 0xef, 0x74, 0xea, 0x3d,
	0xc8, 0x6b, 0x94, 0xa4, 0x87, 0x0e, 0xec, 0x4f, 0xe0, 0xff, 0x21, 0xbd, 0x9f, 0x52, 0xca, 0x57,
	0x14, 0xea, 0xf1, 0x5b, 0xd3, 0xb7, 0xba, 0xb9, 0x49, 0x69, 0xd1, 0x77, 0x86, 0x8c, 0x84, 0x14,
	0xef, 0x04, 0x17, 0x12, 0x16, 0xa0, 0x07, 0x3b, 0x4a, 0x47, 0xa4, 0xaf, 0xe7, 0xf9, 0x82, 0x15,
	0x10, 0x11, 0xca, 0xa9, 0xd2, 0x9c, 0x6f, 0x97, 0x3d, 0xfb, 0x3f, 0x56, 0x4c, 0x7a, 0x25, 0x52,
	0xfe, 0x47, 0x93, 0x4c, 0xe9, 0x1d, 0x26, 0xf9, 0x6b, 0x26, 0x35, 0x96, 0x26, 0x19, 0xfe, 0x83,
	0x8d, 0x8a, 0x61, 0xb7, 0xd0, 0xba, 0xa7, 0x47, 0x2d, 0xa8, 0x8c, 0xd5, 0x34, 0xe6, 0xe2, 0x17,
	0xb4, 0xc0, 0x5c, 0xa9, 0x14, 0xa9, 0xf1, 0xa7, 0xb4, 0x79, 0xa5, 0x26, 0xde, 0xfb, 0xea, 0x42,
	0xdd, 0xc0, 0x2b, 0xd2, 0x33, 0x31, 0x26, 0xec, 0x43, 0xf5, 0xcc, 0xfe, 0x83, 0xb8, 0xc2, 0x6d,
	0x37, 0xd6, 0x9d, 0xf1, 0x5b, 0x9f, 0x7f, 0xfe, 0xfa, 0xe2, 0x36, 0xfc, 0x5a, 0x30, 0x7b, 0x6e,
	0x9f, 0x98, 0xb4, 0xef, 0x1c, 0xe3, 0x39, 0x54, 0x2f, 0x89, 0x07, 0x52, 0xe2, 0x5e, 0xc1, 0x5f,
	0xb9, 0xf2, 0x36, 0x6e, 0xdb, 0xeb, 0x3f, 0xb2, 0x42, 0x75, 0x5c, 0x0a, 0xe1, 0x00, 0x76, 0x2e,
	0x89, 0xed, 0x72, 0xaf, 0xb6, 0x80, 0xdb, 0x1b, 0xec, 0xef, 0xdb, 0xea, 0x26, 0x36, 0x16, 0xd5,
	0xc1, 0x47, 0x11, 0x7d, 0xc2, 0x33, 0x80, 0x37, 0xf6, 0xa5, 0xd8, 0x52, 0xd9, 0x1c, 0xe4, 0xc0,
	0x2a, 0xec, 0xf5, 0x36, 0x14, 0xfa, 0xce, 0xf1, 0x75, 0xd5, 0xbe, 0x88, 0x27, 0x7f, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x07, 0x44, 0xa4, 0xe7, 0x49, 0x05, 0x00, 0x00,
}
